import type { Metadata } from "next";
import { geistSans, geistMono, zenMaruGothic, notoSansJp } from "@/lib/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${zenMaruGothic.variable} ${notoSansJp.variable} h-full antialiased`}
    >
      <body className="min-h-dvh flex items-center justify-center p-6 overflow-hidden">{children}</body>
    </html>
  );
}
